# Generated by Django 4.2.6 on 2023-10-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
    ]
